#!/bin/sh
# Copyright (C) 2016 evenS

version=0.1.3
install(){
    cp -r overwrite.css /www/turbo-static/turbo/v2/style/overwrite.css
    cp -r overbackgroud.css /www/turbo-static/turbo/v2/style/overbackgroud.css
    cp -r bg.png /www/turbo-static/turbo/v2/img/bg.png
    cp -r leve-line3@2x.png /www/turbo-static/turbo/v2/img/leve-line3@2x.png
    cp -r leve-line3.png /www/turbo-static/turbo/v2/img/leve-line3.png
    if [  `grep -c "overwrite.css"  /usr/lib/lua/luci/view/admin_web/header.htm` = 0 ]; then
        echo "" >> /usr/lib/lua/luci/view/admin_web/header.htm
		echo -en "\n<link rel=\"stylesheet\" type=\"text/css\" href=\"<%=resource%>/v2/style/overwrite.css?v=$version\">" >> /usr/lib/lua/luci/view/admin_web/header.htm
	fi
    if [ !-f "/etc/market/Bing.script" -a `grep -c "overbackgroud.css"  /usr/lib/lua/luci/view/admin_web/header.htm` = 0 ]; then
        echo -en "\n<link rel=\"stylesheet\" type=\"text/css\" href=\"<%=resource%>/v2/style/overbackgroud.css?v=$version\">" >> /usr/lib/lua/luci/view/admin_web/header.htm
    fi
}

uninstall(){
    sed -i "\#<link rel=\"stylesheet\" type=\"text/css\" href=\"<%=resource%>/v2/style/overwrite.css?v=$version\">#d" /usr/lib/lua/luci/view/admin_web/header.htm
    sed -i "\#<link rel=\"stylesheet\" type=\"text/css\" href=\"<%=resource%>/v2/style/overbackgroud.css?v=$version\">#d" /usr/lib/lua/luci/view/admin_web/header.htm
    rm -rf /www/turbo-static/turbo/v2/style/overwrite.css
    rm -rf /www/turbo-static/turbo/v2/style/overbackgroud.css
    \cp -r /rom/www/turbo-static/turbo/v2/img/bg.png /www/turbo-static/turbo/v2/img/bg.png
    \cp -r /rom/usr/lib/lua/luci/view/admin_web/header.htm /usr/lib/lua/luci/view/admin_web/header.htm

}
